package gemini

import "testing"

func TestCoerceStringArray(t *testing.T) {
	cases := []struct {
		name    string
		input   any
		wantOK  bool
		wantLen int
	}{
		{"real array", []any{"line one", "line two"}, true, 2},
		{"json-encoded string quirk", `["line one", "line two", "line three"]`, true, 3},
		{"empty array", []any{}, false, 0},
		{"empty string", "", false, 0},
		{"malformed json string", "not json", false, 0},
		{"wrong type", 42, false, 0},
		{"nil", nil, false, 0},
		{"array with empty strings filtered", []any{"", "real line", ""}, true, 1},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			lines, ok := CoerceStringArray(tc.input)
			if ok != tc.wantOK {
				t.Fatalf("ok = %v, want %v (lines=%v)", ok, tc.wantOK, lines)
			}
			if ok && len(lines) != tc.wantLen {
				t.Fatalf("len(lines) = %d, want %d (lines=%v)", len(lines), tc.wantLen, lines)
			}
		})
	}
}

func TestBuildBoardContent(t *testing.T) {
	t.Run("show_working with real lines", func(t *testing.T) {
		board, ok := BuildBoardContent("show_working", map[string]any{
			"title": "Step 1",
			"lines": []any{"The area is $A = \\pi r^2$"},
		})
		if !ok {
			t.Fatal("expected ok=true")
		}
		if board.Kind != "lines" || board.Title != "Step 1" || len(board.Lines) != 1 {
			t.Fatalf("unexpected board: %+v", board)
		}
	})

	t.Run("show_working with quirky string-encoded lines", func(t *testing.T) {
		board, ok := BuildBoardContent("show_working", map[string]any{
			"lines": `["first line", "second line"]`,
		})
		if !ok || len(board.Lines) != 2 {
			t.Fatalf("expected coerced lines, got ok=%v board=%+v", ok, board)
		}
	})

	t.Run("show_working with empty lines fails", func(t *testing.T) {
		_, ok := BuildBoardContent("show_working", map[string]any{"lines": []any{}})
		if ok {
			t.Fatal("expected ok=false for empty lines")
		}
	})

	t.Run("draw_diagram with real mermaid", func(t *testing.T) {
		board, ok := BuildBoardContent("draw_diagram", map[string]any{
			"mermaid": "graph TD; A-->B;",
		})
		if !ok || board.Kind != "diagram" || board.Mermaid == "" {
			t.Fatalf("unexpected result: ok=%v board=%+v", ok, board)
		}
	})

	t.Run("draw_diagram with blank mermaid fails", func(t *testing.T) {
		_, ok := BuildBoardContent("draw_diagram", map[string]any{"mermaid": "   "})
		if ok {
			t.Fatal("expected ok=false for blank mermaid")
		}
	})

	t.Run("chat_checkin with real message", func(t *testing.T) {
		board, ok := BuildBoardContent("chat_checkin", map[string]any{"message": "Does this make sense so far?"})
		if !ok || board.Kind != "chat" || board.Message == "" {
			t.Fatalf("unexpected result: ok=%v board=%+v", ok, board)
		}
	})

	t.Run("chat_checkin with blank message fails", func(t *testing.T) {
		_, ok := BuildBoardContent("chat_checkin", map[string]any{"message": "   "})
		if ok {
			t.Fatal("expected ok=false for blank message")
		}
	})

	t.Run("unknown tool name fails", func(t *testing.T) {
		_, ok := BuildBoardContent("update_board", map[string]any{"step": 1})
		if ok {
			t.Fatal("expected ok=false for unhandled tool name")
		}
	})
}

func TestBoardKey(t *testing.T) {
	a, _ := BuildBoardContent("show_working", map[string]any{"title": "Step 1", "lines": []any{"line one", "line two"}})
	b, _ := BuildBoardContent("show_working", map[string]any{"title": "Step 1 (retry)", "lines": []any{"line one", "line two"}})
	c, _ := BuildBoardContent("show_working", map[string]any{"title": "Step 1", "lines": []any{"line one", "a different line"}})

	if BoardKey(a) != BoardKey(b) {
		t.Fatalf("identical lines with a different title should key the same (title varies on repeats in practice): %q != %q", BoardKey(a), BoardKey(b))
	}
	if BoardKey(a) == BoardKey(c) {
		t.Fatalf("genuinely different lines should not key the same: %q", BoardKey(a))
	}

	// The exact real-world shape observed in practice: a restated board
	// with different whitespace on wrapped bullet lines, cut off partway
	// through with a trailing "…" instead of a byte-for-byte repeat.
	original, _ := BuildBoardContent("show_working", map[string]any{
		"title": "Maximizing Profit",
		"lines": []any{
			"Maximizing profit is a fundamental goal of business management. It generally involves two primary strategies:",
			"1.  **Increasing Revenue:** Revenue is the total income generated by sales of goods or services. To increase revenue, businesses might:",
			"    *   Raise prices (if market conditions allow).",
		},
	})
	restatedTruncated, _ := BuildBoardContent("show_working", map[string]any{
		"lines": []any{
			"Maximizing profit is a fundamental goal of business management. It generally involves two primary strategies:",
			"1.  **Increasing Revenue:** Revenue is the total income generated by sales of goods or services. To increase revenue, businesses might:",
			"*   Raise prices (if market conditions allow)…",
		},
	})
	if BoardKey(original) != BoardKey(restatedTruncated) {
		t.Fatalf("a whitespace-varied, truncated restatement should key the same as the original: %q != %q", BoardKey(original), BoardKey(restatedTruncated))
	}
}
